version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./backend/dynamodb-local:/app/data
    ports:
      - 8000:8000
    expose:
      - "8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /app/data/"

  project:
    container_name: project
    image: project
    build:
      context: ./backend/project
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - "8080"
    links:
      - "dynamodb:db"
      - "frontend:fe"

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./test-app
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    expose:
      - "5173"
    volumes: 
      - ./test-app/src:/app/src
    # environment:
    #   NODE_OPTIONS: --openssl-legacy-provider


volumes:
  app:
